# Generated by Django 5.0.3 on 2024-03-12 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookCategories', '0001_initial'),
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookCategories.bookcategory'),
        ),
        migrations.DeleteModel(
            name='BookCategory',
        ),
    ]
